version: 0.2

env:
  parameter-store:
    GITHUB_USERNAME: '/jenkins/github/username'
    GITHUB_ACCESS_TOKEN: '/jenkins/github/accesstoken'
phases:
  pre_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/version.sh
      - ./gradlew build --dry-run --configure-on-demand --daemon
  build:
    commands:
      - ./gradlew clean build
      - echo "----------------------------------------"
      - ls -l
      - echo "----------------------------------------"
      - ls -alR build/libs
      - ./gradlew publish